from __future__ import annotations

from collections.abc import Sequence
from typing import Protocol
from uuid import UUID

from products.contract.domain.contract import Contract
from products.contract.domain.customer import Customer
from products.contract.domain.version import ContractVersion


class CustomerRepository(Protocol):
    async def add(self, customer: Customer) -> Customer: ...
    async def get(self, user_id: int, customer_id: int) -> Customer | None: ...
    async def list(self, user_id: int) -> Sequence[Customer]: ...
    async def update(self, customer: Customer) -> Customer: ...
    async def delete(self, user_id: int, customer_id: int) -> bool: ...


class ContractRepository(Protocol):
    async def add(self, contract: Contract) -> Contract: ...
    async def get(self, user_id: int, contract_id: UUID) -> Contract | None: ...
    async def list(self, user_id: int) -> Sequence[Contract]: ...


class ContractVersionRepository(Protocol):
    async def add(self, version: ContractVersion) -> ContractVersion: ...
    async def get(self, user_id: int, version_id: UUID) -> ContractVersion | None: ...
    async def list(self, user_id: int, contract_id: UUID) -> Sequence[ContractVersion]: ...
