# Generated by Django 5.2.12 on 2026-04-01 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='新对话', max_length=255, verbose_name='会话标题')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='User.user', verbose_name='用户ID')),
            ],
            options={
                'verbose_name': '用户对话会话',
                'verbose_name_plural': '用户对话会话',
                'db_table': 'user_conversations',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(verbose_name='用户问题')),
                ('ai_response', models.TextField(verbose_name='AI模型返回内容')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='对话时间')),
                ('conversation', models.ForeignKey(blank=True, db_column='conversation_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='User.userconversation', verbose_name='会话文件夹ID')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='User.user', verbose_name='用户ID')),
            ],
            options={
                'verbose_name': '用户会话',
                'verbose_name_plural': '用户会话',
                'db_table': 'user_sessions',
                'ordering': ['-created_at'],
            },
        ),
    ]
