# Generated by Django 5.2.12 on 2026-04-06 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0006_interviewconversation_interviewsession'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userconversation',
            options={'ordering': ['-pinned', 'pinned_at', '-updated_at'], 'verbose_name': '用户对话会话', 'verbose_name_plural': '用户对话会话'},
        ),
    ]
