"""
Django settings for backend_langchain project.

Generated by 'django-admin startproject' using Django 5.2.12.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

from common.extend import apply_hf_mirror_default
from env.provider import settings_conf
from .logger import LOGGING

os.environ.setdefault("HF_HUB_VERBOSITY", "error")
os.environ.setdefault("TRANSFORMERS_VERBOSITY", "error")

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

_S = settings_conf()
_S.apply_llm_env()
# 尽早设置 HF 镜像（与 docker-compose 中 HF_ENDPOINT 一致；未设置时默认 hf-mirror）
apply_hf_mirror_default()


def _cfg_get(path: str, default=None):
    return _S.cfg_get(path, default)


def _env_first(env_name: str, yaml_path: str, default=None):
    v = os.environ.get(env_name)
    if v is not None and str(v).strip() != "":
        return v
    got = _cfg_get(yaml_path)
    return default if got is None else got


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = _env_first(
    "DJANGO_SECRET_KEY",
    "django.secret_key",
    "django-insecure-$fnhz32w$lylbzr0s7hts%zvru#ei#8!)097f5m*l+#*(z9qh0",
)

# SECURITY WARNING: don't run with debug turned on in production!
if os.environ.get("DJANGO_DEBUG") is not None:
    DEBUG = os.environ.get("DJANGO_DEBUG", "True").lower() in ("1", "true", "yes")
else:
    _dbg = _cfg_get("django.debug")
    DEBUG = True if _dbg is None else bool(_dbg)

_allowed = os.environ.get("DJANGO_ALLOWED_HOSTS", "").strip()
if _allowed:
    ALLOWED_HOSTS = [h.strip() for h in _allowed.split(",") if h.strip()]
else:
    _hosts = _cfg_get("django.allowed_hosts")
    if isinstance(_hosts, list):
        ALLOWED_HOSTS = [str(h).strip() for h in _hosts if str(h).strip()]
    else:
        ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # 第三方应用
    'rest_framework',
    'corsheaders',
    # 自定义应用
    'User',
    'Langchain_Agent.apps.LangchainAgentConfig',
    'Langchain_Agent1.apps.LangchainAgent1Config',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# CORS配置
CORS_ALLOW_ALL_ORIGINS = True
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_HEADERS = [
    '*',
    'content-type',
    'authorization',
    'x-requested-with',
]

ROOT_URLCONF = 'backend_langchain.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend_langchain.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': _env_first('MYSQL_DATABASE', 'mysql.database', 'langchain'),
        'USER': _env_first('MYSQL_USER', 'mysql.user', 'root'),
        'PASSWORD': _env_first('MYSQL_PASSWORD', 'mysql.password', 'root'),
        'HOST': _env_first('MYSQL_HOST', 'mysql.host', 'localhost'),
        'PORT': str(_env_first('MYSQL_PORT', 'mysql.port', '3306')),
        'OPTIONS': {
            'charset': 'utf8mb4',
        },
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


