"""Phase 1 Contract schema migration. Apply explicitly with the project's migration runner."""

CREATE_CONTRACT_SCHEMA_SQL = """
CREATE TABLE IF NOT EXISTS contract_customers (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL REFERENCES users(user_id),
    name VARCHAR(255) NOT NULL,
    email VARCHAR(320) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS ix_contract_customers_user_id ON contract_customers(user_id);

CREATE TABLE IF NOT EXISTS contracts (
    id UUID PRIMARY KEY,
    user_id INTEGER NOT NULL REFERENCES users(user_id),
    customer_id INTEGER NOT NULL REFERENCES contract_customers(id),
    title VARCHAR(255) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS ix_contracts_user_id ON contracts(user_id);
CREATE INDEX IF NOT EXISTS ix_contracts_customer_id ON contracts(customer_id);

CREATE TABLE IF NOT EXISTS contract_versions (
    id UUID PRIMARY KEY,
    contract_id UUID NOT NULL REFERENCES contracts(id),
    number INTEGER NOT NULL CHECK (number > 0),
    source_key VARCHAR(1024) NOT NULL,
    filename VARCHAR(512) NOT NULL,
    status VARCHAR(32) NOT NULL DEFAULT 'created',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_contract_versions_contract_number UNIQUE (contract_id, number)
);
CREATE INDEX IF NOT EXISTS ix_contract_versions_contract_id ON contract_versions(contract_id);
"""
