from __future__ import annotations

from typing import Protocol
from uuid import UUID

from products.contract.domain.review import ReviewContext, VersionContent
from products.contract.schemas.analysis import ContractAnalysis


class ContractDocumentParser(Protocol):
    async def parse(self, context: ReviewContext) -> VersionContent: ...


class ContractReviewer(Protocol):
    async def review(self, document_text: str) -> ContractAnalysis: ...


class ContractReviewRepository(Protocol):
    async def claim(self, run_id: UUID) -> ReviewContext | None: ...
    async def get_content(self, version_id: UUID) -> VersionContent | None: ...
    async def mark_parsing(self, context: ReviewContext) -> None: ...
    async def save_content(self, content: VersionContent) -> None: ...
    async def mark_analyzing(self, context: ReviewContext) -> None: ...
    async def complete(
        self,
        context: ReviewContext,
        result: ContractAnalysis,
    ) -> None: ...
    async def fail(self, run_id: UUID, message: str) -> None: ...
